# Generated by Django 5.1.3 on 2024-11-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandata',
            name='emis_paid_on_time',
            field=models.IntegerField(default=0),
        ),
    ]
